//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaderBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Board
    {
        public string BoardId { get; set; }
        public string UserId { get; set; }
        public int Score { get; set; }
        public int GamesPlayed { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
